name: SeaTable Python SDK

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: pip install
        run: |
          pip install --upgrade pip
          pip install requests

      - name: run dateutils test
        run: |
          python ../../tests/dateutils_test
